#!/usr/bin/env /bin/bash

export ETCDCTL_PEERS=$ETCD_NODES

etcdctl=/opt/etcd/etcdctl
restart_lock=$ETCD_PREFIX/restartlock
restarting=$($etcdctl get $restart_lock)
last_restart=$(cat /var/lib/zookeeper/last_restart)
now=$(date +%s)
elapsed=$((now - last_restart))

if [[ $elapsed -lt $ZK_STABILIZATION_SECS ]]; then
  exit 0
fi

echo $now > /var/lib/zookeeper/last_restart

if [[ "$restarting" -eq $ZK_HOSTNAME ]]; then 
  exit 0
fi

until $etcdctl mk $restart_lock $ZK_HOSTNAME --ttl 60 ; do
  sleep 5
done

supervisorctl -c /etc/supervisor/supervisord.conf restart zookeeper

$etcdctl rm $restart_lock

