#!/usr/bin/env /bin/bash

export ETCDCTL_PEERS=$ETCD_NODES

etcdctl=/opt/etcd/etcdctl
myid=`cat /var/lib/zookeeper/myid`
etcdpath=$ETCD_PREFIX/servers/host$myid

function _term() {
  $etcdctl rm $etcdpath
  pkill --parent $child 
  kill $child
}

trap _term EXIT SIGTERM

$etcdctl set $etcdpath >/dev/null <<EOF
{
  "id": "$myid",
  "host": "$ZK_HOSTNAME",
  "peerPort": "$ZK_PEERPORT",
  "leaderPort": "$ZK_LEADERPORT"
}
EOF

exec /opt/zookeeper/bin/zkServer.sh start-foreground /var/lib/zookeeper/zoo.cfg

child=$!
wait $child
