#!/usr/bin/env /bin/bash

export ETCDCTL_PEERS=$ETCD_NODES

etcdctl=/opt/etcd/etcdctl
myid=`cat /var/lib/zookeeper/myid`
etcdpath=$ETCD_PREFIX/servers/host$myid

function _term() {
  $etcdctl rm $etcdpath
  kill $child >/dev/null 2>&1
  wait $child
  exit $?
}

trap _term EXIT SIGTERM

$etcdctl set $etcdpath >/dev/null <<EOF
{
  "id": "$myid",
  "host": "$ZK_HOSTNAME",
  "peerPort": "$ZK_PEERPORT",
  "leaderPort": "$ZK_LEADERPORT"
}
EOF

ZOOBINDIR=/opt/zookeeper/bin
ZOOCONFDIR=/opt/zookeeper/conf
ZOOCFGDIR=/var/lib/zookeeper
ZOOMAIN="org.apache.zookeeper.server.quorum.QuorumPeerMain"

. "$ZOOBINDIR/zkEnv.sh"

"$JAVA" "-Dzookeeper.log.dir=\"${ZOO_LOG_DIR}\"" "-Dzookeeper.root.logger=$ZK_LOGLEVEL,CONSOLE" \
    "-Dlog4j.configuration=$ZOOCONFDIR/log4j.properties" -cp "$CLASSPATH" $JVMFLAGS $ZOOMAIN "$ZOOCFG" &

child=$!
wait $child
